name: lex_test

on:
    push:
        branches: [ task6 ]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: |
                cd ./task6
                mkdir task-ci/3rdparty
                git clone https://github.com/google/googletest.git task-ci/3rdparty
                cd ./task-ci
                cmake -B build
                cmake --build build
                cd ..
                cd ..

            - uses: akhtyamovpavel/ActionGtestReport@v0.0.9
              with:
                exec-path: ./task6/task-ci/bin/CTestExe
                report-path: ./task6/report.xml
                working-directory: ./task6


            - name: Test
              uses: actions/upload-artifact@v3
              with:
                name: test-report
                path: &{{github.workspace}}/task6/report.xml


            - name: UploadArtifacts
              uses: actions/upload-artifact@v3
              with:
                name: Distributive
                path: |
                    ./task6/task-ci/bin
                    ./task6/task-ci/lib
