name: lex_test

on:
    push:
        branches: [ task6 ]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: |
                mkdir ./task6/task-ci/3rdparty
                git clone https://github.com/google/googletest.git ./task6/task-ci/3rdparty
                cd ./task6/task-ci
                cmake -B build
                cd ..
                cd ..
                cmake --build ./task6/task-ci/build

            - uses: akhtyamovpavel/ActionGtestReport@v0.0.9
              with:
                exec-path: "./task6/task-ci/bin/CTestExe"
                report-path: "./task6/report.xml"
                working-directory: "./task6/task-ci"


            - name: Test
              uses: actions/upload-artifact@v3
              with:
                name: test-report
                path: ./task6/report.xml


            - name: UploadArtifacts
              uses: actions/upload-artifact@v3
              with:
                name: Distributive
                path: |
                    ./task6/task-ci/bin
                    ./task6/task-ci/lib
